import { Platform } from 'react-native';
import { RFPercentage, } from "react-native-responsive-fontsize";

export default {

    // size: {
    //     "_10px": RFPercentage(0.135 * 10),
    //     "_11px": RFPercentage(0.135 * 11),
    //     "_12px": RFPercentage(0.135 * 12),
    //     "_13px": RFPercentage(0.135 * 13),
    //     "_14px": RFPercentage(0.135 * 14),
    //     "_15px": RFPercentage(0.135 * 15),
    //     "_16px": RFPercentage(0.135 * 16),
    //     "_17px": RFPercentage(0.135 * 17),
    //     "_18px": RFPercentage(0.135 * 18),
    //     "_19px": RFPercentage(0.135 * 19),
    //     "_20px": RFPercentage(0.135 * 20),
    //     "_21px": RFPercentage(0.135 * 21),
    //     "_22px": RFPercentage(0.135 * 22),
    //     "_23px": RFPercentage(0.135 * 23),
    //     "_24px": RFPercentage(0.135 * 24),
    //     "_25px": RFPercentage(0.135 * 25),
    //     "_26px": RFPercentage(0.135 * 26),
    //     "_27px": RFPercentage(0.135 * 27),
    //     "_28px": RFPercentage(0.135 * 28),
    //     "_29px": RFPercentage(0.135 * 29),
    //     "_30px": RFPercentage(0.135 * 30),
    //     "_31px": RFPercentage(0.135 * 31),
    //     "_32px": RFPercentage(0.135 * 32),
    //     "_33px": RFPercentage(0.135 * 33),
    //     "_34px": RFPercentage(0.135 * 34),
    //     "_50px": RFPercentage(0.135 * 50),
    // },


    size: {
        "_10px": 10,
        "_11px": 11,
        "_12px": 12,
        "_13px": 13,
        "_14px": 14,
        "_15px": 15,
        "_16px": 16,
        "_17px": 17,
        "_18px": 18,
        "_19px": 19,
        "_20px": 20,
        "_21px": 21,
        "_22px": 22,
        "_23px": 23,
        "_24px": 24,
        "_25px": 25,
        "_26px": 26,
        "_27px": 27,
        "_28px": 28,
        "_29px": 29,
        "_30px": 30,
        "_31px": 31,
        "_32px": 32,
        "_33px": 33,
        "_34px": 34,
        "_50px": 50,
    },
    name: {
        Heavy: Platform.OS == "ios" ? 'EuclidCircular_Bold' : "EuclidCircular_Bold",
        regular: Platform.OS == "ios" ? 'EuclidCircular_Regular' : 'EuclidCircular_Regular',
        bold: Platform.OS == "ios" ? 'EuclidCircular_Bold' : 'EuclidCircular_Bold',
        medium: Platform.OS == "ios" ? 'EuclidCircular_Medium' : "EuclidCircular_Medium",
        semibold: Platform.OS == "ios" ? 'EuclidCircular_SemiBold' : 'EuclidCircular_SemiBold',
        light: Platform.OS == "ios" ? 'EuclidCircular_Light' : 'EuclidCircular_Light',
    }
    // name: {
    //     Heavy: Platform.OS == "ios" ? 'SFProText-Heavy' : "sf_pro_text_heavy",
    //     regular: Platform.OS == "ios" ? 'SFProText-Regular' : "sf_pro_text",
    //     bold: Platform.OS == "ios" ? 'SFProText-Bold' : "sf_pro_text_bold",
    //     medium: Platform.OS == "ios" ? 'SFProText-Medium' : "sf_pro_text_medium",
    //     semibold: Platform.OS == "ios" ? 'SFProText-Semibold' : "sf_pro_text_semibold",
    //     light: Platform.OS == "ios" ? 'SFProText-Light' : "sf_pro_text_light",
    // }
    // name: {
    //     Heavy:'SFProText-Heavy',
    //     regular: 'SFProText-Regular',
    //     bold: 'SFProText-Bold',
    //     medium: 'SFProText-Medium',
    //     semibold: 'SFProText-Semibold',
    //     light: 'SFProText-light',
    //     Italic: 'SFProText-Italic',

    //     LightItalic:'SFProText-LightItalic',
    //     HeavyItalic:'SFProText-HeavyItalic',
    //     SemiboldItalic:'SFProText-SemiboldItalic',
    //     MediumItalic:'SFProText-MediumItalic',
    //     BoldItalic:'SFProText-BoldItalic',
    // }
}