export default {
    ic_introimage: require("../../res/ic_splash.png"),
    ic_yelowsoft_logo: require('../../res/commonImages/yelowsoft_logo.png'),
    ic_google: require('../../res/commonImages/google.png'),
    ic_apple: require('../../res/commonImages/apple.png'),
    ic_email: require('../../res/commonImages/Mail.png'),
    ic_SideSettingUnSelectedIcon: require('../../res/commonImages/ic_SideSettingUnSelectedIcon.png'),
    ic_search: require('../../res/commonImages/ic_SideSettingUnSelectedIcon.png'),
    ic_pin: require('../../res/commonImages/ic_SideSettingUnSelectedIcon.png'),
    ic_mic: require('../../res/commonImages/ic_SideSettingUnSelectedIcon.png'),
    ic_more_options: require('../../res/commonImages/more.png'),
    ic_home: require('../../res/commonImages/ic_SideSettingUnSelectedIcon.png'),
    ic_round_trip: require('../../res/commonImages/flag.png'),
    ic_break: require('../../res/commonImages/ic_SideSettingUnSelectedIcon.png'),
    ic_location: require('../../res/commonImages/ic_SideSettingUnSelectedIcon.png'),
    ic_optimize: require('../../res/commonImages/ic_SideSettingUnSelectedIcon.png'),
    ic_chevron_right: require('../../res/commonImages/arrow_right.png'),
    ic_chevron_left: require('../../res/commonImages/ic_SideSettingUnSelectedIcon.png'),
    ic_drawer_menu: require('../../res/commonImages/ic_SideSettingUnSelectedIcon.png'),
    ic_empty_route: require('../../res/commonImages/ic_SideSettingUnSelectedIcon.png'),
    ic_map: require('../../res/commonImages/ic_SideSettingUnSelectedIcon.png'),
    ic_scan: require('../../res/commonImages/ic_SideSettingUnSelectedIcon.png'),
    ic_voice: require('../../res/commonImages/ic_SideSettingUnSelectedIcon.png'),
    ic_mic_small: require('../../res/commonImages/ic_SideSettingUnSelectedIcon.png'),
    // Icons for location details card
    ic_camera: require('../../res/commonImages/camera.png'),
    ic_package_finder: require('../../res/commonImages/ic_SideSettingUnSelectedIcon.png'),
    ic_packages: require('../../res/commonImages/ic_SideSettingUnSelectedIcon.png'),
    ic_order: require('../../res/commonImages/ic_SideSettingUnSelectedIcon.png'),
    ic_type: require('../../res/commonImages/ic_SideSettingUnSelectedIcon.png'),
    ic_arrival_time: require('../../res/commonImages/ic_SideSettingUnSelectedIcon.png'),
    ic_time_at_stop: require('../../res/commonImages/ic_SideSettingUnSelectedIcon.png'),
    ic_change_address: require('../../res/commonImages/ic_SideSettingUnSelectedIcon.png'),
    ic_duplicate_stop: require('../../res/commonImages/ic_SideSettingUnSelectedIcon.png'),
    ic_remove_stop: require('../../res/commonImages/ic_SideSettingUnSelectedIcon.png'),
    // Icons for route details
    ic_close: require('../../res/commonImages/ic_SideSettingUnSelectedIcon.png'),
    ic_time: require('../../res/commonImages/clock.png'),
    // Navigation icons
    ic_back: require('../../res/commonImages/back_arrow.png'),
    // Circuit optimization icons
    ic_distance: require('../../res/commonImages/ic_SideSettingUnSelectedIcon.png'),
    ic_start: require('../../res/commonImages/ic_SideSettingUnSelectedIcon.png'),
    ic_share: require('../../res/commonImages/share.png'),
    // Added icons for location action sheet
    ic_navigation: require('../../res/commonImages/ic_SideSettingUnSelectedIcon.png'),
    ic_make_next: require('../../res/commonImages/ic_SideSettingUnSelectedIcon.png'),
    ic_failed: require('../../res/commonImages/ic_SideSettingUnSelectedIcon.png'),
    ic_delivered: require('../../res/commonImages/ic_SideSettingUnSelectedIcon.png'),
    ic_notes: require('../../res/commonImages/ic_notes.png'),
    ic_edit: require('../../res/commonImages/ic_SideSettingUnSelectedIcon.png'),
    ic_copy: require('../../res/commonImages/ic_SideSettingUnSelectedIcon.png'),
    ic_delete: require('../../res/commonImages/ic_SideSettingUnSelectedIcon.png'),
    ic_help: require('../../res/commonImages/help.png'),
    ic_subscribe: require('../../res/commonImages/subscribe.png'),
    ic_add: require('../../res/commonImages/add.png'),
    ic_arrow_left: require('../../res/commonImages/arrow_left.png'),
    ic_arrow_right: require('../../res/commonImages/arrow_right.png'),
    ic_check: require('../../res/commonImages/Checkmark.png'),
    ic_cross: require('../../res/commonImages/ic_CloseRedIcon.png'),
    ic_calendar: require('../../res/commonImages/ic_calendar.png'),
    ic_radio_button_on: require('../../res/commonImages/ic_radio_button_on.png'),
    ic_radio_button_off: require('../../res/commonImages/ic_radio_button_off.png'),
    ic_location_live: require('../../res/commonImages/ic_location_live.png'),
    ic_checkbox_unchecked: require('../../res/commonImages/ic_checkbox_unchecked.png'),
    ic_checkbox_checked: require('../../res/commonImages/ic_checkbox_checked.png'),
    ic_Chat_Bubbles_Question: require('../../res/commonImages/ic_Chat_Bubbles_Question.png'),
    ic_pin_location: require('../../res/commonImages/ic_pin.png'),
    ic_pin_location_live: require('../../res/commonImages/icMarkerPINDropoff.png'),
    ic_dot: require('../../res/commonImages/ic_dot.png'),

    // lottie animations
    Add_Location: require('../../res/lottie/Add_Location.json'),
    Break_Time: require('../../res/lottie/Break_Time.json'),
    Burger_Menu: require('../../res/lottie/Burger_Menu.json'),
    Car: require('../../res/lottie/Car.json'),
    Delivery_Time: require('../../res/lottie/Delivery_Time.json'),
    Duplicate_Tool: require('../../res/lottie/Duplicate_Tool.json'),
    Edit_Map_Location: require('../../res/lottie/Edit_Map_Location.json'),
    Gps: require('../../res/lottie/Gps.json'),
    Home: require('../../res/lottie/Home.json'),
    Layers: require('../../res/lottie/Layers.json'),
    logistic_packages: require('../../res/lottie/logistic_packages.json'),
    Menu: require('../../res/lottie/Menu.json'),
    Order: require('../../res/lottie/Order.json'),
    OrderType: require('../../res/lottie/OrderType.json'),
    Plus: require('../../res/lottie/Plus.json'),
    Remove: require('../../res/lottie/Remove.json'),
    Return: require('../../res/lottie/Return.json'),
    Search: require('../../res/lottie/Search.json'),
    Start: require('../../res/lottie/Start.json'),
    Stop_Watch: require('../../res/lottie/Stop_Watch.json'),
    Stop: require('../../res/lottie/Stop.json'),
    IC_Package: require('../../res/lottie/IC_Package.json'),
}